// <auto-generated />
using System;
using LinkAcademicoEmpreendedor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkAcademicoEmpreendedor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608223945_AddMoedasEgressoMercadoPago")]
    partial class AddMoedasEgressoMercadoPago
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnoConclusao")
                        .HasColumnType("int");

                    b.Property<int?>("AnoIngresso")
                        .HasColumnType("int");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("AreaId1")
                        .HasColumnType("int");

                    b.Property<string>("ComprovanteAcademico")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Curriculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Curso")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EhEgresso")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FotoPerfil")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GitHub")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Habilidades")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Instituicao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LinkedIn")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Matricula")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("MatriculaValidada")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SaldoMoedas")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sobre")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("TokenExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenRecuperacao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AreaId1");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Área padrão / multiáreas",
                            Nome = "Interdisciplinar"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Ciências da Computação, Sistemas, TI",
                            Nome = "Tecnologia"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Medicina, Enfermagem, Farmácia",
                            Nome = "Saúde"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Engenharias diversas",
                            Nome = "Engenharia"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Ciências Jurídicas",
                            Nome = "Direito"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Administração, Economia",
                            Nome = "Negócios"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Design, Artes Visuais, Multimídia",
                            Nome = "Design/Artes"
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Pedagogia, Educação",
                            Nome = "Educação"
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Sociologia, Psicologia, Antropologia",
                            Nome = "Ciências Sociais"
                        });
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.AssinaturaPremium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("PixCopiaECola")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PixQrCodeBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanoPremiumId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("PlanoPremiumId");

                    b.ToTable("AssinaturasPremium");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvaliadoId")
                        .HasColumnType("int");

                    b.Property<int>("AvaliadorId")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<int?>("OportunidadeId")
                        .HasColumnType("int");

                    b.Property<string>("TipoAvaliado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoAvaliador")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Candidatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCandidatura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataVisualizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("MensagemApresentacao")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("MensagemResposta")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("MoedasGastas")
                        .HasColumnType("int");

                    b.Property<int>("OportunidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OportunidadeId");

                    b.HasIndex("AlunoId", "OportunidadeId")
                        .IsUnique();

                    b.ToTable("Candidaturas");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataComentario")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.CompraMoedas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("MercadoPagoPaymentId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Pacote")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("PagoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("PixCopiaECola")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PixQrCodeBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeMoedas")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TicketUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("ComprasMoedas");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Curtida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCurtida")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("AlunoId", "EmpresaId", "ProjetoId")
                        .IsUnique()
                        .HasFilter("[AlunoId] IS NOT NULL AND [EmpresaId] IS NOT NULL");

                    b.ToTable("Curtidas");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaAtuacao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<DateTime?>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("LogoEmpresa")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NaturezaJuridica")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeResponsavel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SituacaoCadastral")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.FieldDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("bit");

                    b.Property<string>("OpcoesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("FieldDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 2,
                            Nome = "GitHub",
                            Obrigatorio = false,
                            Ordem = 1,
                            Tipo = "url"
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 2,
                            Nome = "StackUtilizada",
                            Obrigatorio = true,
                            Ordem = 2,
                            Tipo = "string"
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 2,
                            Nome = "Tecnologias",
                            Obrigatorio = false,
                            Ordem = 3,
                            Tipo = "string"
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 2,
                            Nome = "Deploy",
                            Obrigatorio = false,
                            Ordem = 4,
                            Tipo = "string"
                        },
                        new
                        {
                            Id = 5,
                            AreaId = 2,
                            Nome = "DocumentacaoTecnica",
                            Obrigatorio = false,
                            Ordem = 5,
                            Tipo = "textarea"
                        },
                        new
                        {
                            Id = 10,
                            AreaId = 3,
                            Nome = "AreaPesquisaClinica",
                            Obrigatorio = true,
                            Ordem = 1,
                            Tipo = "string"
                        },
                        new
                        {
                            Id = 11,
                            AreaId = 3,
                            Nome = "InstituicaoAplicacao",
                            Obrigatorio = true,
                            Ordem = 2,
                            Tipo = "string"
                        },
                        new
                        {
                            Id = 12,
                            AreaId = 3,
                            Nome = "MetodologiaCientifica",
                            Obrigatorio = true,
                            Ordem = 3,
                            Tipo = "textarea"
                        },
                        new
                        {
                            Id = 13,
                            AreaId = 3,
                            Nome = "ArtigosReferencias",
                            Obrigatorio = false,
                            Ordem = 4,
                            Tipo = "textarea"
                        },
                        new
                        {
                            Id = 14,
                            AreaId = 3,
                            Nome = "AprovacaoEtica",
                            Obrigatorio = false,
                            Ordem = 5,
                            Tipo = "boolean"
                        },
                        new
                        {
                            Id = 15,
                            AreaId = 3,
                            Nome = "DocumentoCientifico",
                            Obrigatorio = false,
                            Ordem = 6,
                            Tipo = "file"
                        },
                        new
                        {
                            Id = 20,
                            AreaId = 4,
                            Nome = "MateriaisUtilizados",
                            Obrigatorio = false,
                            Ordem = 1,
                            Tipo = "textarea"
                        },
                        new
                        {
                            Id = 21,
                            AreaId = 4,
                            Nome = "CalculosNormas",
                            Obrigatorio = true,
                            Ordem = 2,
                            Tipo = "textarea"
                        },
                        new
                        {
                            Id = 22,
                            AreaId = 4,
                            Nome = "SoftwaresUtilizados",
                            Obrigatorio = false,
                            Ordem = 3,
                            Tipo = "string"
                        },
                        new
                        {
                            Id = 23,
                            AreaId = 4,
                            Nome = "ModelosProjetos",
                            Obrigatorio = false,
                            Ordem = 4,
                            Tipo = "file"
                        },
                        new
                        {
                            Id = 30,
                            AreaId = 7,
                            Nome = "FerramentasUtilizadas",
                            Obrigatorio = false,
                            Ordem = 1,
                            Tipo = "string"
                        },
                        new
                        {
                            Id = 31,
                            AreaId = 7,
                            Nome = "BehanceFigma",
                            Obrigatorio = false,
                            Ordem = 2,
                            Tipo = "url"
                        },
                        new
                        {
                            Id = 32,
                            AreaId = 7,
                            Nome = "Prototipo",
                            Obrigatorio = false,
                            Ordem = 3,
                            Tipo = "url"
                        },
                        new
                        {
                            Id = 40,
                            AreaId = 5,
                            Nome = "AreaJuridica",
                            Obrigatorio = true,
                            Ordem = 1,
                            Tipo = "string"
                        },
                        new
                        {
                            Id = 41,
                            AreaId = 5,
                            Nome = "CasoEstudo",
                            Obrigatorio = false,
                            Ordem = 2,
                            Tipo = "textarea"
                        },
                        new
                        {
                            Id = 42,
                            AreaId = 5,
                            Nome = "DocumentoDrive",
                            Obrigatorio = false,
                            Ordem = 3,
                            Tipo = "url"
                        },
                        new
                        {
                            Id = 50,
                            AreaId = 6,
                            Nome = "MercadoAlvo",
                            Obrigatorio = false,
                            Ordem = 1,
                            Tipo = "string"
                        },
                        new
                        {
                            Id = 51,
                            AreaId = 6,
                            Nome = "PlanoNegocios",
                            Obrigatorio = false,
                            Ordem = 2,
                            Tipo = "textarea"
                        },
                        new
                        {
                            Id = 60,
                            AreaId = 9,
                            Nome = "Metodologia",
                            Obrigatorio = false,
                            Ordem = 1,
                            Tipo = "textarea"
                        },
                        new
                        {
                            Id = 61,
                            AreaId = 9,
                            Nome = "Referencias",
                            Obrigatorio = false,
                            Ordem = 2,
                            Tipo = "textarea"
                        });
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("int");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TipoDestinatario")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Oportunidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<int>("CustoMoedasCandidatura")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Local")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requisitos")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("VagaPremiumEgresso")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Oportunidades");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.PlanoPremium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beneficios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PlanosPremium");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beneficios = "Selo premium no perfil; vagas priorizadas na lista de oportunidades; mais visibilidade para empresas",
                            Nome = "Core",
                            Ordem = 1,
                            ValorMensal = 59.90m
                        },
                        new
                        {
                            Id = 2,
                            Beneficios = "Tudo do Core; filtros avançados na busca de talentos; acesso ampliado a talentos recentes",
                            Nome = "Advanced",
                            Ordem = 2,
                            ValorMensal = 119.90m
                        },
                        new
                        {
                            Id = 3,
                            Beneficios = "Tudo do Advanced; destaque máximo; mais projetos em destaque; visão ampliada de talentos",
                            Nome = "Advanced Plus",
                            Ordem = 3,
                            ValorMensal = 149.90m
                        });
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ArquivoPdf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("DadosDinamicosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImagemCapa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkDemonstracao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LinkRepositorio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Tecnologias")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.ProjetoLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("ProjetoLinks");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.RedeSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Plataforma")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("RedesSociais");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Aluno", b =>
                {
                    b.HasOne("LinkAcademicoEmpreendedor.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LinkAcademicoEmpreendedor.Models.Area", null)
                        .WithMany("Alunos")
                        .HasForeignKey("AreaId1");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.AssinaturaPremium", b =>
                {
                    b.HasOne("LinkAcademicoEmpreendedor.Models.Empresa", "Empresa")
                        .WithMany("AssinaturasPremium")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkAcademicoEmpreendedor.Models.PlanoPremium", "PlanoPremium")
                        .WithMany()
                        .HasForeignKey("PlanoPremiumId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("PlanoPremium");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Candidatura", b =>
                {
                    b.HasOne("LinkAcademicoEmpreendedor.Models.Aluno", "Aluno")
                        .WithMany("Candidaturas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LinkAcademicoEmpreendedor.Models.Oportunidade", "Oportunidade")
                        .WithMany("Candidaturas")
                        .HasForeignKey("OportunidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Oportunidade");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Comentario", b =>
                {
                    b.HasOne("LinkAcademicoEmpreendedor.Models.Aluno", "Aluno")
                        .WithMany("Comentarios")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LinkAcademicoEmpreendedor.Models.Empresa", "Empresa")
                        .WithMany("Comentarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LinkAcademicoEmpreendedor.Models.Projeto", "Projeto")
                        .WithMany("Comentarios")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Empresa");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.CompraMoedas", b =>
                {
                    b.HasOne("LinkAcademicoEmpreendedor.Models.Aluno", "Aluno")
                        .WithMany("ComprasMoedas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Curtida", b =>
                {
                    b.HasOne("LinkAcademicoEmpreendedor.Models.Aluno", "Aluno")
                        .WithMany("Curtidas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LinkAcademicoEmpreendedor.Models.Empresa", "Empresa")
                        .WithMany("Curtidas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LinkAcademicoEmpreendedor.Models.Projeto", "Projeto")
                        .WithMany("Curtidas")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Empresa");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.FieldDefinition", b =>
                {
                    b.HasOne("LinkAcademicoEmpreendedor.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Oportunidade", b =>
                {
                    b.HasOne("LinkAcademicoEmpreendedor.Models.Empresa", "Empresa")
                        .WithMany("Oportunidades")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Projeto", b =>
                {
                    b.HasOne("LinkAcademicoEmpreendedor.Models.Aluno", "Aluno")
                        .WithMany("Projetos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.ProjetoLink", b =>
                {
                    b.HasOne("LinkAcademicoEmpreendedor.Models.Projeto", "Projeto")
                        .WithMany("Links")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.RedeSocial", b =>
                {
                    b.HasOne("LinkAcademicoEmpreendedor.Models.Aluno", "Aluno")
                        .WithMany("RedesSociais")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LinkAcademicoEmpreendedor.Models.Empresa", "Empresa")
                        .WithMany("RedesSociais")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Aluno");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Aluno", b =>
                {
                    b.Navigation("Candidaturas");

                    b.Navigation("Comentarios");

                    b.Navigation("ComprasMoedas");

                    b.Navigation("Curtidas");

                    b.Navigation("Projetos");

                    b.Navigation("RedesSociais");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Area", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Empresa", b =>
                {
                    b.Navigation("AssinaturasPremium");

                    b.Navigation("Comentarios");

                    b.Navigation("Curtidas");

                    b.Navigation("Oportunidades");

                    b.Navigation("RedesSociais");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Oportunidade", b =>
                {
                    b.Navigation("Candidaturas");
                });

            modelBuilder.Entity("LinkAcademicoEmpreendedor.Models.Projeto", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Curtidas");

                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
